# Generated by Django 5.2.4 on 2025-08-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(related_name='services_offered', to='core.master'),
        ),
    ]
