# Generated by Django 5.2.4 on 2025-08-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ai_checked_status',
            field=models.CharField(choices=[('ai_checked_true', 'Проверено ИИ'), ('ai_cancelled', 'Отменено ИИ'), ('ai_checked_in_progress', 'В процессе проверки'), ('ai_checked_false', 'Не проверено')], default='ai_checked_false', max_length=30, verbose_name='Статус ИИ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(related_name='services_offered', to='core.master', verbose_name='Мастера'),
        ),
    ]
